name: Deploy functions on push/merge

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-functions-prod.yml'
      - 'functions/**'
  pull_request:
    branches-ignore:
      - '!main'
    types: [ closed ]
    paths:
      - '.github/workflows/deploy-functions-prod.yml'
      - 'functions/**'

jobs:
  build:
    name: Publish changes

    runs-on: ubuntu-latest

    steps:
      # Get the repo files from current commit
      - name: Cloning repository
        uses: actions/checkout@v1

      # Install frontend dependencies based on nvmrc
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvmfunctions
        working-directory: functions

      - name: Set Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvmfunctions.outputs.NVMRC }}"

      - name: Install functions dependencies
        run: npm i
        working-directory: functions

          
      - name: Deploy to Firebase
        uses: docker://w9jds/firebase-action:master
        with:
          # Enable --force since merging from dev should never require a manual deploy
          args: deploy --force --only=functions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
